### ISSUE TITLE
root needs to be mounted as shared on windows

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/rancher-desktop-wsl-distro#1]
Something like this command will do it:

```
wsl --user root -d k3s mount --make-shared /
```

**Comment by jandubois** [comment]
This is being done by Rancher Desktop itself; there is no way to do this inside the distro tarball.

It could be added to e.g. the `run-k3s` script, but that too is supposed to be moved to the rancher-desktop repo.
